# Stubs for pymc3.glm.linear (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..model import Model
from typing import Any, Optional

class LinearComponent(Model):
    default_regressor_prior: Any = ...
    default_intercept_prior: Any = ...
    coeffs: Any = ...
    y_est: Any = ...
    def __init__(self, x: Any, y: Any, intercept: bool = ..., labels: Optional[Any] = ..., priors: Optional[Any] = ..., vars: Optional[Any] = ..., name: str = ..., model: Optional[Any] = ..., offset: float = ...) -> None: ...
    @classmethod
    def from_formula(cls,
                     formula: Any,
                     data: Any,
                     priors: Optional[Any] = ...,
                     vars: Optional[Any] = ...,
                     name: str = ...,
                     model: Optional[Any] = ...,
                     offset: float = ...): ...

class GLM(LinearComponent):
    y_est: Any = ...
    def __init__(self, x: Any, y: Any, intercept: bool = ..., labels: Optional[Any] = ..., priors: Optional[Any] = ..., vars: Optional[Any] = ..., family: str = ..., name: str = ..., model: Optional[Any] = ..., offset: float = ...) -> None: ...

glm = GLM

