# Stubs for pymc3.glm.utils (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def any_to_tensor_and_labels(x: Any, labels: Optional[Any] = ...): ...
