# Stubs for pymc3.backends (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from typing_extensions import Protocol

# from the source
from ..backends.ndarray import NDArray as NDArray, save_trace as save_trace, load_trace as load_trace
from ..backends.text import Text as Text
from ..backends.sqlite import SQLite as SQLite
from ..backends.hdf5 import HDF5 as HDF5
from pymc3 import _Point

from .base import MultiTrace as MultiTrace
from typing_extensions import Protocol

# This might need some more methods for the protocol
class Backend(Protocol):
    def record(self, _Point) -> None: ...
    
