# Stubs for pymc3.backends.tracetab (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def trace_to_dataframe(trace: Any, chains: Optional[Any] = ..., varnames: Optional[Any] = ..., include_transformed: bool = ...): ...
