# Stubs for pymc3.examples.custom_dists (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

theta_true: Any
xdata: Any
ydata: Any
data: Any

def loglike1(value: Any): ...
def loglike2(value: Any): ...

alpha: Any
beta: Any
sigma: Any
like: Any
trace: Any

def compute_sigma_level(trace1: Any, trace2: Any, nbins: int = ...): ...
def plot_MCMC_trace(ax: Any, xdata: Any, ydata: Any, trace: Any, scatter: bool = ..., **kwargs: Any) -> None: ...
def plot_MCMC_model(ax: Any, xdata: Any, ydata: Any, trace: Any) -> None: ...
def plot_MCMC_results(xdata: Any, ydata: Any, trace: Any, colors: str = ...) -> None: ...

pymc3_trace: Any
