# Stubs for pymc3.examples.disaster_model (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

disasters_data: Any
switchpoint: Any
early_mean: Any
late_mean: Any
rate: Any
disasters: Any
