# Stubs for pymc3.examples.gelman_bioassay (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

n: Any
dose: Any
alpha: Any
beta: Any
theta: Any
deaths: Any

def run(n: int = ...) -> None: ...
