# Stubs for pymc3.examples.gelman_schools (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

J: int
y: Any
sigma: Any
eta: Any
mu: Any
tau: Any
theta: Any
obs: Any

def run(n: int = ...) -> None: ...
