# Stubs for pymc3.examples.GHME_2013 (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

data: Any
countries: Any
age: Any
rate: Any
group: Any
ncountries: Any
d: Any
nknots: int
knots: Any

def interpolate(x0: Any, y0: Any, x: Any, group: Any): ...

coeff_sd: Any
y: Any
p: Any
sd: Any
vals: Any

def run(n: int = ...) -> None: ...
