# Stubs for pymc3.examples.lightspeed_example (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

light_speed: Any
model_1: Any
mu: Any
sigma: Any
y_obs: Any

def run(n: int = ...) -> None: ...
