# Stubs for pymc3.examples.LKJ_correlation (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

n_obs: int
mu_r: Any
n_var: Any
stds: Any
corr_r: Any
cov_matrix: Any
dataset: Any
mu: Any
sd_dist: Any
packed_chol: Any
chol: Any
cov: Any
sd: Any
corr: Any
r: Any
like: Any

def run(n: int = ...) -> None: ...
