# Stubs for pymc3.examples.rankdata_ordered (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

K: int
J: int
yreal: Any
y: Any
y_argsort: Any
mu_hat: Any
mu: Any
latent: Any

def run(n: int = ...) -> None: ...
