# Stubs for pymc3.examples.samplers_mvnormal (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

USE_XY: bool

def run(steppers: Any, p: Any): ...
