# Stubs for pymc3.examples.simpletest (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

data: Any
x: Any
z: Any
d: Any

def run(n: int = ...) -> None: ...
