# Stubs for pymc3.step_methods.hmc (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .hmc import HamiltonianMC as HamiltonianMC
from .nuts import NUTS as NUTS

