# Stubs for pymc3.tuning (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .scaling import approx_hessian, find_hessian, guess_scaling, trace_cov
from .starting import find_MAP
