# Stubs for pymc3.variational (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .approximations import Empirical, FullRank, MeanField, NormalizingFlow, sample_approx
from .inference import ADVI, ASVGD, FullRankADVI, ImplicitGradient, Inference, KLqp, NFVI, SVGD, fit
from .opvi import Approximation, Group
from .stein import Stein
from .updates import adadelta, adagrad, adagrad_window, adam, adamax, apply_momentum, apply_nesterov_momentum, momentum, nesterov_momentum, norm_constraint, rmsprop, sgd, total_norm_constraint
