# Stubs for pymc3.variational.test_functions (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .opvi import TestFunction
from typing import Any

class Kernel(TestFunction): ...

class RBF(Kernel):
    def __call__(self, X: Any): ...

rbf: Any
