# Stubs for pymc3.util (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List

from .distributions.transforms import Transform

RV = Any # variable type.

def escape_latex(strng: str) -> str: ...
def get_transformed_name(name: str, transform: Transform) -> str: ...
def is_transformed_name(name: str) -> bool: ...
def get_untransformed_name(name: str) -> str: ...
def get_default_varnames(var_iterator: Any, include_transformed: Any) -> List[str]: ...


# The following are all pretty opaque in their meaning and type.  I'm
# going to hope that no external user will need to know their types,
# and comment them out.[2018/11/12:rpg]s



# the following returns a variable's name if the argument is a variable. If it's a constant,
# it returns the data type instead.
# def get_variable_name(variable: Any) -> Any: ... 
# def update_start_vals(a: Any, b: Any, model: Any) -> None: ...
# def get_transformed(z: Any) -> Any: ...
# def biwrap(wrapper: Any): ...

