# Stubs for pymc3.vartypes (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

string_types = basestring

bool_types: Any
int_types: Any
float_types: Any
complex_types: Any
continuous_types: Any
discrete_types: Any

def typefilter(vars: Any, types: Any): ...
def isgenerator(obj: Any): ...
