# Stubs for pymc3.distributions (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# straight from the source
from . import timeseries as timeseries
from . import transforms as transforms

from .continuous import Uniform as Uniform
from .continuous import Flat as Flat
from .continuous import HalfFlat as HalfFlat
from .continuous import TruncatedNormal as TruncatedNormal
from .continuous import Normal as Normal
from .continuous import Beta as Beta
from .continuous import Kumaraswamy as Kumaraswamy
from .continuous import Exponential as Exponential
from .continuous import Laplace as Laplace
from .continuous import StudentT as StudentT
from .continuous import Cauchy as Cauchy
from .continuous import HalfCauchy as HalfCauchy
from .continuous import Gamma as Gamma
from .continuous import Weibull as Weibull
from .continuous import HalfStudentT as HalfStudentT
from .continuous import Lognormal as Lognormal
from .continuous import ChiSquared as ChiSquared
from .continuous import HalfNormal as HalfNormal
from .continuous import Wald as Wald
from .continuous import Pareto as Pareto
from .continuous import InverseGamma as InverseGamma
from .continuous import ExGaussian as ExGaussian
from .continuous import VonMises as VonMises
from .continuous import SkewNormal as SkewNormal
from .continuous import Triangular as Triangular
from .continuous import Gumbel as Gumbel
from .continuous import Logistic as Logistic
from .continuous import LogitNormal as LogitNormal
from .continuous import Interpolated as Interpolated
from .continuous import Rice as Rice

from .discrete import Binomial as Binomial
from .discrete import BetaBinomial as BetaBinomial
from .discrete import Bernoulli as Bernoulli
from .discrete import DiscreteWeibull as DiscreteWeibull
from .discrete import Poisson as Poisson
from .discrete import NegativeBinomial as NegativeBinomial
from .discrete import ConstantDist as ConstantDist
from .discrete import Constant as Constant
from .discrete import ZeroInflatedPoisson as ZeroInflatedPoisson
from .discrete import ZeroInflatedNegativeBinomial as ZeroInflatedNegativeBinomial
from .discrete import ZeroInflatedBinomial as ZeroInflatedBinomial
from .discrete import DiscreteUniform as DiscreteUniform
from .discrete import Geometric as Geometric
from .discrete import Categorical as Categorical
from .discrete import OrderedLogistic as OrderedLogistic

from .distribution import DensityDist as DensityDist
from .distribution import Distribution as Distribution
from .distribution import Continuous as Continuous
from .distribution import Discrete as Discrete
from .distribution import NoDistribution as NoDistribution
from .distribution import TensorType as TensorType
from .distribution import draw_values as draw_values
from .distribution import generate_samples as generate_samples

from .mixture import Mixture as Mixture
from .mixture import NormalMixture as NormalMixture

from .multivariate import MvNormal as MvNormal
from .multivariate import MatrixNormal as MatrixNormal
from .multivariate import KroneckerNormal as KroneckerNormal
from .multivariate import MvStudentT as MvStudentT
from .multivariate import Dirichlet as Dirichlet
from .multivariate import Multinomial as Multinomial
from .multivariate import Wishart as Wishart
from .multivariate import WishartBartlett as WishartBartlett
from .multivariate import LKJCholeskyCov as LKJCholeskyCov
from .multivariate import LKJCorr as LKJCorr

from .timeseries import AR1 as AR1
from .timeseries import AR as AR
from .timeseries import GaussianRandomWalk as Gaussian
from .timeseries import GARCH11 as GARCH11
from .timeseries import MvGaussianRandomWalk as MvGaussianRandomWalk
from .timeseries import MvStudentTRandomWalk as MvStudentTRandomWalk

from .transforms import transform as transform
from .transforms import stick_breaking as stick_breaking
from .transforms import logodds as logodds
from .transforms import log as log
from .transforms import sum_to_1 as sum_to_1

from .bound import Bound as Bound
