# Stubs for pymc3.distributions.special (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

gammaln: Any

def multigammaln(a: Any, p: Any): ...
def log_i0(x: Any): ...

psi: Any
