# Stubs for pymc3.tests.checks (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def close_to(x: Any, v: Any, bound: Any, name: str = ...) -> None: ...
def close_to_logical(x: Any, v: Any, bound: Any, name: str = ...) -> None: ...
