# Stubs for pymc3.tests.test_pickling (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .models import simple_model

class TestPickling:
    def setup_method(self) -> None: ...
    def test_model_roundtrip(self) -> None: ...
