# Stubs for pymc3.tests.test_shared (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .helpers import SeededTest

class TestShared(SeededTest):
    def test_deterministic(self) -> None: ...
    def test_sample(self) -> None: ...
