# Stubs for pymc3.tests.test_modelcontext (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class TestModelContext:
    def test_thread_safety(self) -> None: ...
