# Stubs for pymc3.tests.test_special_functions (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .checks import close_to
from typing import Any

def test_functions() -> None: ...
def t_multigamma(): ...
def check_vals(fn1: Any, fn2: Any, *args: Any) -> None: ...
