# Stubs for pymc3.tests.test_model_helpers (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class TestHelperFunc:
    def test_pandas_to_array(self) -> None: ...
    def test_as_tensor(self): ...
