# Stubs for pymc3.plots.autocorrplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import get_axis, get_default_varnames
from typing import Any, Optional

def autocorrplot(trace: Any, varnames: Optional[Any] = ..., max_lag: int = ..., burn: int = ..., plot_transformed: bool = ..., symmetric_plot: bool = ..., ax: Optional[Any] = ..., figsize: Optional[Any] = ...): ...
