# Stubs for pymc3.plots.compareplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def compareplot(comp_df: Any, insample_dev: bool = ..., se: bool = ..., dse: bool = ..., ax: Optional[Any] = ..., plot_kwargs: Optional[Any] = ...): ...
