# Stubs for pymc3.plots.densityplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..stats import hpd
from .kdeplot import fast_kde
from .utils import get_default_varnames
from typing import Any, Optional

def densityplot(trace: Any, models: Optional[Any] = ..., varnames: Optional[Any] = ..., alpha: float = ..., point_estimate: str = ..., colors: str = ..., outline: bool = ..., hpd_markers: str = ..., shade: float = ..., bw: float = ..., figsize: Optional[Any] = ..., textsize: int = ..., plot_transformed: bool = ..., ax: Optional[Any] = ...): ...
def _d_helper(vec: Any, vname: Any, c: Any, bw: Any, alpha: Any, point_estimate: Any, hpd_markers: Any, outline: Any, shade: Any, ax: Any) -> None: ...
