# Stubs for pymc3.plots.energyplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .kdeplot import kdeplot
from typing import Any, Optional

def energyplot(trace: Any, kind: str = ..., figsize: Optional[Any] = ..., ax: Optional[Any] = ..., legend: bool = ..., shade: float = ..., bw: float = ..., frame: bool = ..., kwargs_shade: Optional[Any] = ..., **kwargs: Any): ...
