# Stubs for pymc3.plots.forestplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import get_default_varnames, identity_transform
from typing import Any, Optional

def _var_str(name: Any, shape: Any): ...
def _plot_tree(ax: Any, y: Any, ntiles: Any, show_quartiles: Any, c: Any, plot_kwargs: Any): ...
def forestplot(trace: Any, models: Optional[Any] = ..., varnames: Optional[Any] = ..., transform: Any = ..., alpha: float = ..., quartiles: bool = ..., rhat: bool = ..., main: Optional[Any] = ..., xtitle: Optional[Any] = ..., xlim: Optional[Any] = ..., ylabels: Optional[Any] = ..., colors: str = ..., chain_spacing: float = ..., vline: int = ..., gs: Optional[Any] = ..., plot_transformed: bool = ..., plot_kwargs: Optional[Any] = ...): ...
