# Stubs for pymc3.plots.kdeplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def kdeplot(values: Any, label: Optional[Any] = ..., shade: int = ..., bw: float = ..., ax: Optional[Any] = ..., kwargs_shade: Optional[Any] = ..., **kwargs: Any): ...
def fast_kde(x: Any, bw: float = ...): ...
