# Stubs for pymc3.plots.pairplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..util import get_default_varnames, get_untransformed_name, is_transformed_name
from .artists import get_trace_dict, scale_text
from typing import Any, Optional

def pairplot(trace: Any, varnames: Optional[Any] = ..., figsize: Optional[Any] = ..., text_size: Optional[Any] = ..., gs: Optional[Any] = ..., ax: Optional[Any] = ..., hexbin: bool = ..., plot_transformed: bool = ..., divergences: bool = ..., kwargs_divergence: Optional[Any] = ..., sub_varnames: Optional[Any] = ..., **kwargs: Any): ...
