# Stubs for pymc3.plots.posteriorplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .artists import get_trace_dict, plot_posterior_op, scale_text
from .utils import get_default_varnames, identity_transform
from typing import Any, Optional

def plot_posterior(trace: Any, varnames: Optional[Any] = ..., transform: Any = ..., figsize: Optional[Any] = ..., text_size: Optional[Any] = ..., alpha_level: float = ..., round_to: int = ..., point_estimate: str = ..., rope: Optional[Any] = ..., ref_val: Optional[Any] = ..., kde_plot: bool = ..., plot_transformed: bool = ..., bw: float = ..., ax: Optional[Any] = ..., **kwargs: Any): ...
def plot_posterior_predictive_glm(trace: Any, eval: Optional[Any] = ..., lm: Optional[Any] = ..., samples: int = ..., **kwargs: Any): ...
