# Stubs for pymc3.plots.traceplot (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .artists import histplot_op, kdeplot_op
from .utils import get_axis, get_default_varnames, identity_transform, make_2d
from typing import Any, Optional
from matplotlib.axes import Axes
from numpy import ndarray

# returns an ndarray of Axes, but I don't know how to say that in type hint
def traceplot(trace: Any,
              varnames: Optional[Any] = ...,
              transform: Any = ...,
              figsize: Optional[Any] = ...,
              lines: Optional[Any] = ...,
              combined: bool = ...,
              plot_transformed: bool = ...,
              grid: bool = ...,
              alpha: float = ...,
              priors: Optional[Any] = ...,
              prior_alpha: int = ...,
              prior_style: str = ...,
              bw: float = ...,
              ax: Optional[Any] = ...,
              live_plot: bool = ...,
              skip_first: int = ...,
              refresh_every: int = ...,
              roll_over: int = ...) -> ndarray: ... 
