# Stubs for pymc3.plots.utils (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..util import get_default_varnames as get_default_varnames

from typing import Any

def identity_transform(x: Any): ...
def get_axis(ax: Any, default_rows: Any, default_columns: Any, **default_kwargs: Any): ...
def make_2d(a: Any): ...
